# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot

# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .7

# *Required* Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users.

# Note: the bot will only work if your repository has a Code of Conduct
  
# Configuration for - https://probot.github.io/apps/welcome

newIssueWelcomeComment: >
  Thanks for opening your first issue! Someone will circle back soon âš¡
newPRWelcomeComment: >
  Thanks for opening this pull request! Someone will review it soon ðŸ”
firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you ðŸ¦…
  ![Eagle gif](https://media.giphy.com/media/SLD8eKFPuUDuw/200w_d.gif)
